# Generated by Django 4.0.4 on 2022-05-26 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='static/images/default-pic.png', upload_to='profile_pics')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('address', models.CharField(max_length=20, verbose_name='Address')),
                ('bio', models.TextField(max_length=200, verbose_name='Bio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('img1', models.ImageField(blank=True, null=True, upload_to='posts')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='posts')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='posts')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='posts')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='posts')),
                ('img6', models.ImageField(blank=True, null=True, upload_to='posts')),
                ('img7', models.ImageField(blank=True, null=True, upload_to='posts')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
