# Generated by Django 4.0.4 on 2022-05-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img8',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
