# Generated by Django 4.0.5 on 2022-07-19 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img1',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img6',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img7',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img8',
        ),
    ]
