# Generated by Django 4.0.4 on 2022-05-13 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_profile_bio_profile_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
