# Generated by Django 4.0.4 on 2022-05-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=1, max_length=120, verbose_name='Phone'),
            preserve_default=False,
        ),
    ]
