# Generated by Django 4.0.4 on 2022-05-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default=1, max_length=120, verbose_name='Address'),
            preserve_default=False,
        ),
    ]
