# Generated by Django 4.0.4 on 2022-05-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_profile_address_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=1, max_length=200, verbose_name='Bio'),
            preserve_default=False,
        ),
    ]
